# Generated by Django 2.2.16 on 2022-04-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_category_genre_review_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="reviews.Title",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "пользователь"),
                    ("moderator", "модератор"),
                    ("admin", "администратор"),
                ],
                default="user",
                max_length=25,
                verbose_name="Роль пользователя",
            ),
        ),
    ]
