# Generated by Django 2.2.16 on 2022-04-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["-id"]},
        ),
    ]
