# Generated by Django 2.2.16 on 2022-04-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_comment"),
        ("reviews", "0003_auto_20220415_1047"),
    ]

    operations = []
