# Generated by Django 2.2.16 on 2022-04-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_merge_20220418_0853"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-id"]},
        ),
    ]
